# .github/workflows/preview.yml
name: Deploy PR previews

on:
  # Runs on pull requests targeting the default branch
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: false

# Sets permissions of the GITHUB_TOKEN to allow writing to the gh-pages branch and writing a pull request comment
permissions:
  contents: write
  pull-requests: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch
      - name: Checkout
        uses: actions/checkout@v3
      # Setup Poetry for dependencies
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v8
      # Build the site with Poetry
      - name: Build html
        run: |
          cd docs
          poetry install
          poetry run make html
      # Deploy the preview to a subsite
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: docs/_build/html
          umbrella-dir: pr-preview
          action: auto
