name: Deploy PR preview

on:
  workflow_run:
    workflows: ["Build PR preview"]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: false

# Sets permissions of the GITHUB_TOKEN to allow writing to the gh-pages branch and writing a pull request comment
permissions:
  contents: write
  pull-requests: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      # Download PR build artifact from last run
      # Taken from: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
      - name: 'Download artifact'
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "pr"
            })[0];
            var download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/pr.zip', Buffer.from(download.data));
      
      # Extract artifact, get PR number and store it in env
      - name: Extract artifact and PR number
        run: |
          unzip pr.zip
          echo "pr=$(cat ./NR)" >> $GITHUB_ENV
      
      - name: Deploy preview
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
          destination_dir: pr-preview/pr-${{ env.pr }}/
          keep_files: true
          
      - name: Get Pages URL and datetime
        run: |
          pagesurl=$(echo "$GITHUB_REPOSITORY" | sed 's/\//.github.io\//')
          echo "pagesurl=$pagesurl" >> $GITHUB_ENV
          echo "datetime=$(date '+%Y-%m-%d %H:%M %Z')" >> $GITHUB_ENV
        shell: bash

      - name: Create PR comment
        env:
          preview-branch: 'gh-pages'
          preview-folder: 'pr-preview/pr-${{ env.pr }}'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-preview
          number: ${{ env.pr }}
          message: |
            | PR Preview |
            | :---: |
            | :rocket: Deployed preview to https://${{ env.pagesurl }}/${{ env.preview-folder }} |
            | on branch [`${{ env.preview-branch }}`](${{ github.server_url }}/${{ github.repository }}/tree/${{ env.preview-branch }}) at ${{ env.datetime }} |
